name: artifact-hash

on:
  push:
  pull_request:

jobs:
  generate-artifact-hash:
    if: 1
    needs:
      - auto-cache-pool
      - linux-aarch64
      - linux-x86_64
      - macos-aarch64
      - macos-x86_64
      - windows-cygwin

    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/download-artifact@v4
      - name: Display structure of downloaded files
        run: ｜
          ls -R
          ls -p | grep -v /$ | xargs sha256sum
          ls -p | grep -v /$ | xargs sha256sum > Artifacts.sha256sum

