name: artifact-hash

on:
workflow_dispatch:
  inputs:
    version:
      required: true
      description: "发版版本号 tag"
      default: '--vesion v5.1.6.0'
      type: string

jobs:
  generate-artifact-hash:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Show Release File Hash
        run: ｜
          bash sapi/scripts/generate-artifact-hash.sh

